spring:
  profiles:
    include: infra
    active: dev

server:
  port: 8082

payment:
    toss_test_client_api_key: "test_ck_Gv6LjeKD8aE1pdWDXXNw8wYxAdXy"
    toss_test_secret_api_key: "test_sk_tempSecretKey" # 노출되면 안됨!! 임시값 넣어놓음
    success_url: "https://localhost:8080/api/v1/success"
    fail_url: "https://localhost:8080/api/v1/fail"
