spring:
  profiles:
    include: infra, security
    active: dev

server:
  port: 8082

payment:
  toss:
    test-client-api-key: test_ck_Gv6LjeKD8aE1pdWDXXNw8wYxAdXy
    test-secret-api-key: test_sk_tempSecretKey # 노출되면 안됨!! 임시값 넣어놓음
    success-url: https://localhost:8080/api/v1/success
    fail-url: https://localhost:8080/api/v1/fail
