### 세션 아이디 발급
POST http://localhost:8082/api/v1/bookings/issue-session-id
Authorization: Bearer {{accessToken}}

### 대기열 진입
POST http://localhost:8082/api/v1/bookings/enter-queue
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Booking-Session-Id: {{sessionId}}

{
  "eventId": 1
}

### 대기열 조회
GET http://localhost:8082/api/v1/bookings/order-in-queue?eventId=1
Authorization: Bearer {{accessToken}}
Booking-Session-Id: {{sessionId}}


### 예매 토큰 발급
POST http://localhost:8082/api/v1/bookings/issue-token
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Booking-Session-Id: {{sessionId}}

{
  "eventId": 1
}

### [Optional] 대기열 이탈
POST http://localhost:8082/api/v1/bookings/exit-queue
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Booking-Session-Id: {{sessionId}}

{
  "eventId": 1
}

### 좌석 목록 조회
GET http://localhost:8082/api/v1/seats?eventTimeId=1
Authorization: Bearer {{accessToken}}
Booking-Authorization: Bearer {{bookingToken}}

### 좌석 선택
POST http://localhost:8082/api/v1/seats/1/select
Authorization: Bearer {{accessToken}}
Booking-Authorization: Bearer {{bookingToken}}

### 좌석 선택 해제
POST http://localhost:8082/api/v1/seats/1/deselect
Authorization: Bearer {{accessToken}}
Booking-Authorization: Bearer {{bookingToken}}

### 예매 생성
POST http://localhost:8082/api/v1/bookings/create
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Booking-Authorization: Bearer {{bookingToken}}

{
  "timeId": 1,
  "seatIds": [1],
  "receiptType": "현장수령",
  "buyerName": "빙봉",
  "buyerPhoneNumber": "010-1234-5678"
}

### 예매 ~ 결제 승인 (브라우저에서 진행해 주세요)
GET http://localhost:8082/bookings

### [Optional] 예매 이탈
POST http://localhost:8082/api/v1/bookings/1/exit
Authorization: Bearer {{accessToken}}
Booking-Authorization: Bearer {{bookingToken}}

### 예매 취소 (브라우저에서 생성된 예매 번호로 진행해 주세요)
POST http://localhost:8082/api/v1/bookings/1/cancel
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "cancelReason": "구매자 변심"
}

### 내 예매 내역 목록 조회
GET http://localhost:8082/api/v1/bookings
Authorization: Bearer {{accessToken}}

### 내 예매 내역 상세 조회
GET http://localhost:8082/api/v1/bookings/1705163603493
Authorization: Bearer {{accessToken}}
