spring:
  profiles:
    include: infra
    active: dev

server:
  port: 8085

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type.descriptor: trace
        sql: debug
        orm:
          jdbc.bind: trace
jwt:
  secret-key: secret-key # TODO : 시크릿 키 따로 관리
  expiry-seconds: 3600
