spring:
  profiles:
    include: infra
    active: dev

server:
  port: 8081

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  # H2
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org:
      hibernate:
        type.descriptor: trace
        sql: debug
        orm:
          jdbc.bind: trace

jwt:
  secret-key: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 3600
