spring:
  profiles:
    include: infra, security
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: dhxl50@gmail.com
    password: gmail_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8081

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type.descriptor: trace
        sql: debug
        orm:
          jdbc.bind: trace

