spring:
  profiles:
    include: infra, security
    active: dev

server:
  port: 8081

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type.descriptor: trace
        sql: debug
        orm:
          jdbc.bind: trace
