version: '3'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.9.0
    networks:
      - es_net
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /usr/share/data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ=Asia/Seoul
    user: root
    restart: always
    privileged: true

  kibana:
    container_name: kibana
    image: kibana:7.9.0
    networks:
      - es_net
    ports:
      - 5601:5601
    environment:
      ELASTICSERCH_UTL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      TZ: Asia/Seoul
    restart: always
    privileged: true

networks:
    es_net:
      driver: bridge
