## 어드민

### 어드민 로그인
POST http://localhost:8081/api/v1/auth/admin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "user1234"
}

### 공연장 등록
POST http://localhost:8080/api/v1/event-halls
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpZCI6Miwic3ViIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3MDUwMjQxNzgsImV4cCI6MTcwNTAyNTk3OCwiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9.V5-9yIMRhoIB2ivtCvrZV7I4fTVvlkKyJ6nwA5UpijOolOj8xfc-6WevHDyn5hkc

{
  "name": "잠실 종합운동장",
  "address": "서울특별시 송파구",
  "eventHallSeatCreateRequests": [
    {
      "name": "1A"
    },
    {
      "name": "2A"
    },
    {
      "name": "1B"
    },
    {
      "name": "1Z"
    }
  ]
}

### 공연 등록
POST http://localhost:8080/api/v1/events
Content-Type: application/json

{
  "title": "히사이시 조 영화음악 콘서트",
  "description": "영화보다 빛나는 영화 음악, 그 여운을 다시 한 번! 지브리 스튜디오 미야자키 히야오의 모든 애니메이션 음악을 담당하며 현존하는 최고의 작곡가&지휘자 히사이시 조",
  "runningTime": 100,
  "startedAt": "2024-02-05T12:00:00",
  "endedAt": "2024-02-022T12:00:00",
  "viewRating": "12",
  "genreType": "CONCERT",
  "bookingStartedAt": "2024-01-05T12:00:00",
  "bookingEndedAt": "2024-02-01T12:00:00",
  "eventHallId": 1
}

### 공연 회차 생성
POST http://localhost:8080/api/v1/event-times/2
Content-Type: application/json

{
  "round": 1,
  "startedAt": "2024-02-05T12:00:00",
  "endedAt": "2024-02-05T13:00:00"
}

### 공연 좌석 구역 생성
POST http://localhost:8080/api/v1/events/2/seat-area
Content-Type: application/json

{
  "requests": [
    {
      "seatAreaType": "R",
      "price": 1000
    },
    {
      "seatAreaType": "S",
      "price": 2000
    }
  ]
}

### 공연 좌석 생성
POST http://localhost:8080/api/v1/event-seats/events/2
Content-Type: application/json

[
  {
    "name": "1A",
    "status": "AVAILABLE",
    "eventSeatAreaId": 3
  },
  {
    "name": "1B",
    "status": "AVAILABLE",
    "eventSeatAreaId": 3
  },
  {
    "name": "2A",
    "status": "AVAILABLE",
    "eventSeatAreaId": 3
  },
  {
    "name": "1A",
    "status": "AVAILABLE",
    "eventSeatAreaId": 4
  },
  {
    "name": "1B",
    "status": "AVAILABLE",
    "eventSeatAreaId": 4
  }
]

### 공연 회차 좌석 목록 조회
GET http://localhost:8080/api/v1/event-seats/event-times/2

===

## 멤버

### 회원가입
POST http://localhost:8081/api/v1/members/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password",
  "passwordConfirm": "password",
  "name": "name",
  "phoneNumber": "01012345678",
  "birthDate": "20000101",
  "gender": "MALE",
  "streetAddress": "서울특별시 광진구 능동로",
  "detailAddress": "A동 101호",
  "zipCode": "12345"
}

### 로그인
POST http://localhost:8081/api/v1/auth/members/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### oauth 회원가입/로그인 (Optional)
http://localhost:8081/login

### 내 정보 확인
GET http://localhost:8081/api/v1/members/me
Authorization: Bearer {{accessToken}}

### 공연 목록 - 리뷰순
GET http://localhost:8080/api/v1/events/sort/ranking?page=1&size=10&genreType=CONCERT&dateOffset=7

### 키워드 검색
GET http://localhost:8080/api/v1/events/search/keyword?page=1&size=10&keyword=히사&startedAt=2023-01-01T12:00:00

### 실시간 인기 검색어
GET http://localhost:8080/api/v1/events/search/top-ten

### 공연 회차의 등급별 남은 좌석수 조회
GET http://localhost:8080/api/v1/event-seats/event-times/2/available-numbers

===

## 예매

### 세션 아이디 발급
POST http://localhost:8082/api/v1/bookings/issue-session-id
Authorization: Bearer {{accessToken}}

### 대기열 진입
POST http://localhost:8082/api/v1/bookings/enter-queue
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Booking-Session-Id: {{sessionId}}

{
  "eventId": 1
}

### 대기열 조회
GET http://localhost:8082/api/v1/bookings/order-in-queue?eventId=1
Authorization: Bearer {{accessToken}}
Booking-Session-Id: {{sessionId}}


### 예매 토큰 발급
POST http://localhost:8082/api/v1/bookings/issue-token
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Booking-Session-Id: {{sessionId}}

{
  "eventId": 1
}

### [Optional] 대기열 이탈
POST http://localhost:8082/api/v1/bookings/exit-queue
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Booking-Session-Id: {{sessionId}}

{
  "eventId": 1
}

### 좌석 목록 조회
GET http://localhost:8082/api/v1/seats?eventTimeId=1
Authorization: Bearer {{accessToken}}
Booking-Authorization: Bearer {{bookingToken}}

### 좌석 선택
POST http://localhost:8082/api/v1/seats/1/select
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Booking-Authorization: Bearer {{bookingToken}}

### 좌석 선택 해제
POST http://localhost:8082/api/v1/seats/1/deselect
Content-Type: application/json
Authorization: Bearer {{accessToken}}
Booking-Authorization: Bearer {{bookingToken}}

### 예매 ~ 결제 승인 (브라우저에서 진행해 주세요)
GET http://localhost:8082/bookings

### [Optional] 예매 이탈
POST http://localhost:8082/api/v1/bookings/1/exit
Authorization: Bearer {{accessToken}}
Booking-Authorization: Bearer {{bookingToken}}

### 예매 취소 (브라우저에서 생성된 예매 번호로 진행해 주세요)
POST http://localhost:8082/api/v1/bookings/1/cancel
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "cancelReason": "구매자 변심"
}

### 내 예매 내역 목록 조회
GET http://localhost:8082/api/v1/bookings
Authorization: Bearer {{accessToken}}

### 내 예매 내역 상세 조회
GET http://localhost:8082/api/v1/bookings/{bookingId}
Authorization: Bearer {{accessToken}}
