## 어드민

### 어드민 로그인

### 공연장 등록

### 공연 등록

### 공연 회차 생성

### 공연 좌석 구역 생성

### 공연 좌석 생성

### 공연 회차 좌석 목록 조회

===

## 멤버

### 회원가입

### 로그인

### 내 정보 확인

### 공연 목록 - 랭킹

### 공연 id로 조회

### 공연 회차의 등급별 남은 좌석수 조회

### 예매 플로우 복붙

### 내 예매 조회

