spring:
  profiles:
    include: infra
    active: dev

server:
  port: 8080

cloud:
  aws:
    s3:
      bucket: bingterparkbucket
    credentials:
      access-key: <access-key 입력>
      secret-key: <secret-key 입력> # 노출되면 안되는 값
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret-key: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ # TODO : 시크릿 키 따로 관리
  expiry-seconds: 360000000
