@token = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6Mywic3ViIjoiZGh4bDUwQG5hdmVyLmNvbSIsImlhdCI6MTcwNDYxNjU4NSwiZXhwIjoyMDY0NjE2NTg1LCJhdXRob3JpdHkiOiJST0xFX1VTRVIifQ.OIiQazdvmv-bsZp0VroiouW5gEqNAj7ROqRTOcLbWXQ
@adminToken = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6Miwic3ViIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3MDQ2Mzc1NzgsImV4cCI6MjA2NDYzNzU3OCwiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9.lAXg2NbcVeuSak6IW-AUNKC6zqd_0x_ER8RU3CMxNpk

## AUTH

### 로그인 - 슈퍼 관리자
POST http://localhost:8081/api/v1/auth/admin/login
Content-Type: application/json

{
  "email": "superadmin@example.com",
  "password": "user1234"
}

### 로그인 - 관리자
POST http://localhost:8081/api/v1/auth/admin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "user1234"
}

### 멤버 로그인
POST http://localhost:8081/api/v1/auth/members/login
Content-Type: application/json

{
  "email": "member1@example.com",
  "password": "user1234"
}

### 토큰 갱신
POST http://localhost:8081/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

===

## ADMIN MANAGEMENT

### 관리자 등록 - 슈퍼 관리자
POST http://localhost:8081/api/v1/admin/management
Content-Type: application/json
Authorization: Bearer {{superAdminToken}}

{
  "name": "testAdmin",
  "password": "user1234",
  "passwordConfirm": "user1234",
  "phoneNumber": "01012345678",
  "email": "testAdmin@admin.com",
  "role": "ROLE_ADMIN"
}

### 관리자 목록 조회 - 슈퍼 관리자
GET http://localhost:8081/api/v1/admin/management
Authorization: Bearer {{superAdminToken}}

### 관리자 수정 - 슈퍼 관리자
PATCH http://localhost:8081/api/v1/admin/management/1
Content-Type: application/json
Authorization: Bearer {{superAdminToken}}

{
  "name": "",
  "password": "",
  "passwordConfirm": "",
  "phoneNumber": "",
  "status": "ACTIVE",
  "role": "ROLE_ADMIN"
}

### 관리자 삭제 - 슈퍼 관리자
DELETE http://localhost:8081/api/v1/admin/management?adminIds=1
Authorization: Bearer {{superAdminToken}}

===

## ADMIN

### 로그인 - 관리자
POST http://localhost:8081/api/v1/auth/admin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "user1234"
}

### 관리자 본인 정보 조회
GET http://localhost:8081/api/v1/admin/me
Authorization: Bearer {{adminToken}}

### 관리자 본인 탈퇴
DELETE http://localhost:8081/api/v1/admin/me
Authorization: Bearer {{adminToken}}

### 멤버 정보 조회 - 관리자
GET http://localhost:8081/api/v1/admin/members
Authorization: Bearer {{adminToken}}

### 멤버 상세 정보 조회 - 관리자
GET http://localhost:8081/api/v1/admin/members/details?memberIds=1,2
Authorization: Bearer {{adminToken}}

===

## MEMBER

### 멤버 일반 회원가입
POST http://localhost:8081/api/v1/members/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password",
  "passwordConfirm": "password",
  "name": "name",
  "phoneNumber": "01012345678",
  "birthDate": "20000101",
  "gender": "MALE",
  "streetAddress": "서울특별시 광진구 능동로",
  "detailAddress": "A동 101호",
  "zipCode": "12345"
}

### 멤버 로그인
POST http://localhost:8081/api/v1/auth/members/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### 멤버 OAuth 로그인 / 회원가입 (직접테스트)
http://localhost:8081/login

### 멤버 본인 정보 조회 (토큰 필요)
GET http://localhost:8081/api/v1/members/me
Authorization: Bearer {{token}}

### 멤버 본인 정보 수정 (토큰 필요)
PATCH http://localhost:8081/api/v1/members/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "변경된 이름",
  "phoneNumber": "01099999999",
  "birthDate": "19990101",
  "gender": "MALE",
  "streetAddress": "",
  "detailAddress": "",
  "zipCode": "01012"
}

### 멤버 본인 비밀번호 변경 (토큰 필요, 카카오는 불가능)
PATCH http://localhost:8081/api/v1/members/me/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "originPassword": "",
  "newPassword": "",
  "newPasswordConfirm": ""
}

### 멤버 본인 비밀번호 확인 (토큰 필요, 카카오는 불가능)
POST http://localhost:8081/api/v1/members/me/verify-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "password": ""
}

### 멤버 본인 탈퇴 (토큰 필요)
DELETE http://localhost:8081/api/v1/members/me
Authorization: Bearer {{token}}

### 멤버 계정 복구 (토큰 필요)
POST http://localhost:8081/api/v1/members/restore
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{token}}
