### 로그인 - 슈퍼 관리자
POST http://localhost:8081/api/v1/auth/admin/login
Content-Type: application/json

{
  "email": "superadmin@example.com",
  "password": "user1234"
}

### 로그인 - 관리자
POST http://localhost:8081/api/v1/auth/admin/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "user1234"
}

### 회원 목록 조회
GET http://localhost:8081/api/v1/admin/members
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6Miwic3ViIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3MDQ2MDg3MzQsImV4cCI6MTcwNDYxMDUzNCwiYXV0aG9yaXR5IjoiUk9MRV9BRE1JTiJ9.3EHS2VF2XqW4xfE1W0iFMUaK1P3r2wpFgK9imzw3xp4

### 토큰 갱신
POST http://localhost:8081/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "a718e554-fad4-48c2-a131-d73228937605"
}

### 유저 일반 회원가입
POST http://localhost:8081/api/v1/members/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password",
  "passwordConfirm": "password",
  "name": "name",
  "phoneNumber": "01012345678",
  "birthDate": "20000101",
  "gender": "MALE",
  "streetAddress": "서울특별시 광진구 능동로",
  "detailAddress": "A동 101호",
  "zipCode": "12345"
}

### 유저 로그인
POST http://localhost:8081/api/v1/auth/members/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### 유저 OAuth 로그인 / 회원가입 (직접테스트)
http://localhost:8081/login
