### 로그인 - 슈퍼 관리자
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "email": "superadmin@example.com",
  "password": "user1234"
}

### 로그인 - 관리자
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "user1234"
}

